version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pos:pos@db:5432/vid
      - CDN_HOST=cdn.example.com
      - REDIRECT_RATIO=5
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=pos
      - POSTGRES_PASSWORD=pos
      - POSTGRES_DB=vid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: